name: Check Poco X3 Kernel Config

on:
  workflow_dispatch:

jobs:
  check:

    runs-on: ubuntu-22.04

    steps:

    - name: Install tools
      run: |
        sudo apt update
        sudo apt install -y git


    - name: Clone Xiaomi Kernel Source
      run: |
        git clone \
        -b surya-q-oss \
        --depth=1 \
        https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git kernel


    - name: Find Defconfig
      run: |

        cd kernel

        echo "========================"
        echo "Kernel branch:"
        git branch

        echo "========================"
        echo "Search Poco X3 config"

        find arch/arm64/configs \
        -type f \
        | grep -iE "surya|sm7150|defconfig" || true


        echo "========================"
        echo "List configs"

        ls -la arch/arm64/configs


        echo "========================"
        echo "Vendor folder"

        ls -la arch/arm64/configs/vendor 2>/dev/null || echo "No vendor folder"
