name: Build Poco X3 NFC Kernel

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
        bc \
        bison \
        flex \
        build-essential \
        gcc-aarch64-linux-gnu \
        libssl-dev \
        libelf-dev \
        git


    - name: Clone Xiaomi Kernel Source
      run: |
        git clone \
        -b surya-q-oss \
        --depth=1 \
        https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git kernel


    - name: Fix DTC build
      run: |

        cd kernel

        sed -i \
        '1i #include <stddef.h>' \
        scripts/dtc/dtc-lexer.l


    - name: Configure Kernel
      run: |

        cd kernel

        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-

        mkdir out

        make O=out vendor/atoll_defconfig


    - name: Build Kernel
      run: |

        cd kernel

        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-

        make O=out -j$(nproc)


    - name: Upload Kernel
      uses: actions/upload-artifact@v4
      with:
        name: PocoX3-Kernel
        path: kernel/out/arch/arm64/boot/*
